### PR TITLE
Added preprocessed option in args and updated Readme.

### PR DESCRIPTION
**Pull request by sg60692**
- Added flags in the argument parser
- Fixed wrong number of arguments passed to test in main.py
- Updated Readme with link for preprocessed UCF dataset

### CODE REVIEW

**Comment by KjaMadsen** [comment]
@sg60692 Thanks for the good work. Could you by any chance share the code you used to extract the features on the google drive? I have a custom dataset I would like to test

**Comment by sg60692** [comment]
@KjaMadsen I basically used the code that would run otherwise in the normal pipeline of the dataset.py file for UCF. It is not pretty but I used the following jupyter kernel 
```
import os
import numpy as np
from utils import process_feat
for file in os.listdir("D:/MGFN_UCF_10CROP_DATA/UCF_Train_ten_i3d/"):
    features = np.load("D:/MGFN_UCF_10CROP_DATA/UCF_Train_ten_i3d/"+file, allow_pickle=True)
    features = np.array(features, dtype=np.float32)
    features = features.transpose(1, 0, 2)  # [10, T, F]
    divided_features = []
    divided_mag = []
    for feature in features:
        feature = process_feat(feature, 32) #ucf(32,2048)
        divided_features.append(feature)
        divided_mag.append(np.linalg.norm(feature, axis=1)[:, np.newaxis])
    divided_features = np.array(divided_features, dtype=np.float32)
    divided_mag = np.array(divided_mag, dtype=np.float32)
    divided_features = np.concatenate((divided_features,divided_mag),axis = 2)
    np.save("D:/MGFN_UCF_10CROP_DATA/UCF_Train_ten_i3d_32_seg/"+file[:-4],divided_features)
```
The code inside for loop is copied from the path which would be executed if UCF was used, which is what I added the flag for skipping. Dataset.py currently doesn't handle custom datasets, you would probably have to refactor it based on your current needs

**Comment by GP0123** [comment]
if using the 32 seg data，how to use preprocess flag 。
if not using the 32 seg data，how to modify the option.py

**Comment by GP0123** [comment]
hi
The dataset address you raised cannot be found, and there are files in the unsegmented dataset that are damaged. Therefore, can you provide a new dataset address.Thank you!

**Comment by GP0123** [comment]
Hi， I have run your code for several times， but the AUC is always below 0.7. why？

**Comment by GP0123** [comment]
@KjaMadsen   Hi， I have run your code for several times， but the AUC is always below 0.7. why？

**Comment by GP0123** [comment]
@sg60692  Hi， I have run your code for several times， but the AUC is always below 0.7. why？ I can‘t change the code

**Comment by GP0123** [comment]
@carolchenyx  could you give me your gt file ？ I have run your code for several times，but the AUC is always below 0.7. I use the RTFM gt。

**Comment by zjy56** [comment]
> @sg60692 Thanks for the good work. Could you by any chance share the code you used to extract the features on the google drive? I have a custom dataset I would like to test

Did you find the code for feature extraction later? I also have a dataset that I would like to run, and I would appreciate it if I could share it from you

**Pull request merged**
